### PR TITLE
BUG: No longer read rotation center as index (elastix transform < 3.402)

### PR DESCRIPTION
**Pull request by N-Dekker**
No longer read "CenterOfRotation" from an old transform parameter file, which is the rotation center of the transformation, specified by its index coordinates.

elastix version >= 3.402 no longer specifies the rotation center by its index coordinates.

As explained by Stefan @stefanklein

"Having a center of rotation in index coordinates in the TransformParameter file is bad practice, since its conversion to a world coordinate depends on the knowledge of the size/spacing/origin/directioncosines of the fixed image that was used for registration. That information is stored in the TransformParameter file as well, but it is easy to forget changing the CenterOfRotationIndex when adjusting the (fixed image) resample domain."

Also discussed with Marius @mstaring

Fixes issue #162 ("AffineLogStackTransform: uninitialized local variable 'rdorigin' used")

### CODE REVIEW

**Comment by N-Dekker** [comment]
@stefanklein Shall I also remove the `ReadCenterOfRotationIndex` member functions from `elxAdvancedAffineTransform`, `elxEulerStackTransform`, and `elxEulerTransform`? (It seems that all of them are just for backward compatibility for elastix version < 3.402.)

**Comment by mstaring** [comment]
> 
> 
> @stefanklein Shall I also remove the `ReadCenterOfRotationIndex` member functions from `elxAdvancedAffineTransform`, `elxEulerStackTransform`, and `elxEulerTransform`? (It seems that all of them are just for backward compatibility for elastix version < 3.402.)

I think that is a good idea, since we are moving to a major new version (5.0.0)

**Comment by stefanklein** [comment]
The fix looks good, and I agree that we can remove this from other transforms as well. In elxEulerStackTransform the same function was implemented correctly by the way. But anyway, it's better to remove that functionality everywhere.
Quick recap of reason to deprecate/remove that functionality: Having a center of rotation in index coordinates in the TransformParameter file is bad practice, since its conversion to a world coordinate depends on the knowledge of the size/spacing/origin/directioncosines of the fixed image that was used for registration. That information is stored in the TransformParameter file as well, but it is easy to forget changing the CenterOfRotationIndex when adjusting the (fixed image) resample domain.

**Comment by N-Dekker** [comment]
@stefanklein If you think it's OK, feel free to press the "merge" button 😄

**Pull request merged**
