### PR TITLE
Modernize PrintHelp() and update elastix website URL

### PR DESCRIPTION
**Pull request by N-Dekker**

### CODE REVIEW

**Comment by mstaring** [comment]
lgtm

**Comment by N-Dekker** [comment]
@mstaring @stefanklein Note that this pull request does not address the outdated elastix.isi.uu.nl/legal.php  URLs, as I mentioned in our internal slack channel at https://superelastix.slack.com/archives/C04ESL0G5/p1620828916002600 At:

  https://github.com/SuperElastix/elastix/blob/5.0.1/dox/externalproject/itkTimerTest.cxx#L6
  https://github.com/SuperElastix/elastix/blob/5.0.1/dox/misc/cla/CCLA-elastix.txt#L3
  https://github.com/SuperElastix/elastix/blob/5.0.1/dox/misc/cla/ICLA-elastix.txt#L3
  https://github.com/SuperElastix/elastix/blob/5.0.1/tools/CopyrightNotice_BSD.txt#L6

Could these four legal.php URLs simply be removed? Or should they be replaced by a different URL?

**Comment by mstaring** [comment]
maybe some of them can point to https://github.com/SuperElastix/elastix/wiki/Legal-stuff which is the new place

**Comment by N-Dekker** [comment]
> maybe some of them can point to https://github.com/SuperElastix/elastix/wiki/Legal-stuff which is the new place

Sounds reasonable. Maybe we can discuss at the sprint. Anyway, eventually I think the "legal stuff" is the responsibility of you and @stefanklein If I would make a pull request, I would like one of you to do the "rebase-and-merge".

**Pull request merged**
