### PR TITLE
Support reading Euler and Similarity transforms from ITK (HDF5, TFM) into elastix

### PR DESCRIPTION
**Pull request by N-Dekker**
Regarding issue #464 "Support HDF5 or TFM format for all transforms"

### CODE REVIEW

**Comment by mstaring** [comment]
lgtm

**Comment by N-Dekker** [comment]
@mstaring Just added Similarity support, simply by adding an `if (!this->HasITKTransformParameters())` to the implementation of `SimilarityTransformElastix::ReadFromFile(void)`, meaning that it simply skips reading the `centerOfRotation` when the configuration has "ITKTransformParameters". Does that look OK to you?

Also added unit tests, of course  😃

**Comment by mstaring** [comment]
if the tests work it should be good! The logic makes sense to me.

**Comment by N-Dekker** [comment]
@mstaring Still haven't got elastix Similarity in sync with `itk::Similarity3DTransform`, when both center and scale are set. I don't know but it looks like an ITK issue. 2D and 3D seem to be inconsistent with ITK Similarity as well:

    const auto itkTransform2D = itk::Similarity2DTransform<double>::New();
    itkTransform2D->SetCenter(itk::Point<double, 2>({ 1.0, 1.0 }));
    itkTransform2D->SetScale(2.0);
    std::cout << itkTransform2D->TransformPoint(itk::Point<double, 2>({ 0.0, 0.0 })) << '\n';

Prints: _[-1, -1]_

However, in 3D:

    const auto itkTransform3D = itk::Similarity3DTransform<double>::New();
    itkTransform3D->SetCenter(itk::Point<double>({ 1.0, 1.0, 1.0 }));
    itkTransform3D->SetScale(2.0);
    std::cout << itkTransform3D->TransformPoint(itk::Point<double>({ 0.0, 0.0, 0.0 })) << '\n';

Print: _[0, 0, 0]_

While elastix `SimilarityTransformElastix` produces _[-1, -1]_ for 2D, and _[-1, -1, -1]_ for 3D.

Do you agree that ITK Similarity3DTransform appears wrong in this case?

**Comment by mstaring** [comment]
I am not sure this transform is fully specified with just center and scale. Can you print GetParameters() for both? Perhaps there is an initialization difference.

In principle there are 7 parameters in 3D: 3 rotations, 3 translations, 1 scale

**Comment by N-Dekker** [comment]
> I am not sure this transform is fully specified with just center and scale. Can you print GetParameters() for both? (and also fixed parameters)

2D:
```
ITK Parameters:      [2, 0, 0, 0]
ITK FixedParameters: [1, 1]
ELX Parameters:      [2, 0, 0, 0]
ELX FixedParameters: [1, 1]

```

3D:
```

ITK Parameters:      [0, 0, 0, 0, 0, 0, 2]
ITK FixedParameters: [1, 1, 1]
ELX Parameters:      [0, 0, 0, 0, 0, 0, 2]
ELX FixedParameters: [1, 1, 1]

```

**Comment by mstaring** [comment]
Now that we have confirmed that both parameters and fixed parameters are the same, it is weird that the transformpoint returns different results. Can you compare their implementations, to see what the differences are? Did something change for example in the time we made the elastix copy and now?

**Comment by N-Dekker** [comment]
> are intermediate matrices that the transformpoint function uses, updated correctly?

@mstaring  Ah, now I see, it appears that a call to ITK's `Similarity3DTransform::SetScale` does not update its internal `MatrixOffsetTransformBase::m_Offset`. On the other hand, `SetCenter` and `SetTranslation` do update `m_Offset`, and when the offset is updated, ITK and Elastix produce the same result. 😃 

My workaround for the unit tests is to do the `SetScale` call _before_  calling `SetCenter` and `SetTranslation`, to ensure that the offset is eventually updated. .

**Pull request merged**
