### PR TITLE
STYLE: Remove obsolete Google search bar from Doxygen

### PR DESCRIPTION
**Pull request by N-Dekker**
-- As was discussed with Marius (@mstaring) and Michèle (@mwjhhuijberts)!

M + M, can you please check this pull request?

### CODE REVIEW

**Comment by mstaring** [comment]
lgtm

**Comment by mwjhhuijberts** [comment]
FIne with me.

For future reference:
The quick fix on webserver via:
```
cd ~/www/doxygen/
find . -type f -name \*html | xargs sed -i 's/<gcse:search><\/gcse:search>/<!-- <gcse:search><\/gcse:search> -->/'
```

**Comment by mwjhhuijberts** [comment]
@N-Dekker - when you create a new DoxyGen version, inform me where to download the new release. I will upload it the the webserver.

**Comment by N-Dekker** [comment]
> when you create a new DoxyGen version, inform me where to download the new release. I will upload it the the webserver.

Sure, I will let you know, thanks @mwjhhuijberts !

**Pull request merged**
