### PR TITLE
BUG: Close output streams at the end of GenerateData()

### PR DESCRIPTION
**Pull request by N-Dekker**
Implements the "core part" of issue #297, "Feature Request: Allow closing log file in library"

ITKElastix issue https://github.com/InsightSoftwareConsortium/ITKElastix/issues/61 "Is the log file really closed?"

### CODE REVIEW

**Comment by N-Dekker** [comment]
Discussed with @mstaring and @ViktorvdValk  at our weekly internal Elastix sprint. A more extensive `xoutClose()` function is probably necessary. Such a function would close and clear all internal (global) data that was opened and initialized by `xoutSetup`.

Such a `xoutClose()` function should then be called at the end of a member function like `ElastixRegistrationMethod::GenerateData()`

**Comment by N-Dekker** [comment]
@mstaring This pull request introduces a `xoutManager`, that automatically closes the output streams when the `xoutManager` is destructed (by going out of scope). Please have a look!

**Comment by mstaring** [comment]
to technical for me to judge properly, but overall it looks good to me. Does it solve the problem?

**Comment by N-Dekker** [comment]
> to technical for me to judge properly, but overall it looks good to me. Does it solve the problem?

@mstaring There are ITKElastix packages underway at https://github.com/N-Dekker/ITKElastix/tree/Close-elastix-output-streams  which include this fix. I still have to check if the problem is thereby solved.

Regarding the technicality: the first commit https://github.com/SuperElastix/elastix/pull/303/commits/892dc878ea467382404187fb07fef146e7339e51 has brought all output streams used by `xoutSetup` together in a `Data` struct.  This data object is reset within the destructor of `xoutManager::Guard`, by the assignment `g_data = {};` at https://github.com/SuperElastix/elastix/blob/1068d151ef594a3d7685289d4b99c58d01be86d8/Core/Kernel/elxElastixMain.cxx#L146

That reset should effectively close all streams.

**Comment by N-Dekker** [comment]
I checked this pull request on my forked rebuild of ITKElastix, including this fix, with some help from @ViktorvdValk 

    >>> registered_image, params = itk.elastix_registration_method(fixed_image, moving_image, log_to_file=True, output_directory='D:/X/output/')

Does create a log file, _and_ allows renaming the file without closing the Python session  😃

**Pull request merged**
