### PR TITLE
ImageSpatialObject2 data member cleanup

### PR DESCRIPTION
**Pull request by N-Dekker**
`ImageSpatialObject2` data member cleanup:

* Declared data members `private`
* Declared `m_SlicePosition` as array
* Declared `GetPixelType()` static and removed `m_PixelType`.

### CODE REVIEW

**Comment by N-Dekker** [comment]
@mstaring @stefanklein Are `GetPixelType` and `GetSlicePosition` actually being used?

**Comment by N-Dekker** [comment]
The elastix/ITK4 compile errors at the Azure CI appear unrelated to this pull request.

https://dev.azure.com/kaspermarstal/Elastix/_build/results?buildId=355 says:

    itkAdvancedTransform.h(116): error C2039: 'InverseJacobianPositionType': is not a member of 'itk::Transform<PrecisionType,3,3>'

**Comment by mstaring** [comment]
looks good to me

**Comment by N-Dekker** [comment]
@mstaring 
> looks good to me

Thanks Marius, I'll merge this. Still I wonder: Are GetPixelType and GetSlicePosition actually being used?

**Comment by mstaring** [comment]
I don't know by heart, you would have to check elastix.

**Comment by N-Dekker** [comment]
For the record: `GetPixelType()`is deprecated by now for ITK5
https://github.com/InsightSoftwareConsortium/ITK/pull/667/commits/36afd271a749e499b05b8512b9eca792cdfdd4d8 (to be removed from both `itk::ImageSpatialObject` and `itk::MeshSpatialObject`), so I think it won't harm to remove this member function from elastix either.

**Comment by mstaring** [comment]
Yes. I think the long term solution is to check if the new itk::ImageSpatialObject fixes issues, and that we use that one and remove our version.

**Comment by N-Dekker** [comment]
This pull request is likely to be superseded by #147 (ENH: Replace elastix ImageSpatialObject2 by ITK ImageSpatialObject)

**Comment by N-Dekker** [comment]
This pull request is obsolete, now that `ImageSpatialObject2` has been removed from elastix: https://github.com/SuperElastix/elastix/commit/7c2523a77275317dbd1d104897ef5b6b782e7a8c

**Pull request closed without merging**
