### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by mstaring**

### CODE REVIEW

**Comment by kaspermarstal** [comment]
It looks like this PR broke the ITKv4 build, specifically the itkBSplineDerivativeKernelFunctionTest:

```
[  9%] Building CXX object Testing/CMakeFiles/itkBSplineDerivativeKernelFunctionTest.dir/itkBSplineDerivativeKernelFunctionTest.cxx.o
In file included from /home/vsts/work/1/s/Common/Transforms/itkAdvancedBSplineDeformableTransformBase.h:21:0,
                 from /home/vsts/work/1/s/Common/Transforms/itkAdvancedBSplineDeformableTransform.h:37,
                 from /home/vsts/work/1/s/Testing/itkAdvancedBSplineDeformableTransformTest.cxx:18:
/home/vsts/work/1/s/Common/Transforms/itkAdvancedTransform.h: In instantiation of ‘class itk::AdvancedTransform<float, 3u, 3u>’:
/home/vsts/work/1/s/Common/Transforms/itkAdvancedBSplineDeformableTransformBase.h:42:7:   required from ‘class itk::AdvancedBSplineDeformableTransformBase<float, 3u>’
/home/vsts/work/1/s/Common/Transforms/itkAdvancedBSplineDeformableTransform.h:134:7:   required from ‘class itk::AdvancedBSplineDeformableTransform<float, 3u, 3u>’
/home/vsts/work/1/s/Testing/itkAdvancedBSplineDeformableTransformTest.cxx:66:24:   required from here
/home/vsts/work/1/s/Common/Transforms/itkAdvancedTransform.h:116:60: error: no type named ‘InverseJacobianPositionType’ in ‘class itk::Transform<float, 3u, 3u>’
   typedef typename Superclass::InverseJacobianPositionType InverseJacobianPositionType;
```

Can you take a look @mstaring or perhaps the original author?

**Comment by mstaring** [comment]
yes, we are switching to ITK5.
Can you update the build to work with ITK5?

**Comment by kaspermarstal** [comment]
The build is already working with ITKv5. The failing builds are with ITKv4. Should we remove CI testing with ITKv4?

**Comment by mstaring** [comment]
I believe Niels wants to keep it for the moment. 

He just merged a fix for this issue.

**Pull request merged**
