### PR TITLE
ENH: Remove dynamic exception specifications which are deprecated in C++11

### PR DESCRIPTION
**Pull request by kaspermarstal**

### CODE REVIEW

**Comment by mstaring** [comment]
I can't really judge. THis is something we simply copied from the ITK previously. If this is removed in ITK5 now, then for me this is enough reason the also remove it in elastix. Is it?

**Comment by kaspermarstal** [comment]
What does ITK do now?

**Comment by N-Dekker** [comment]
@kaspermarstal 
> What does ITK do now?

As far as I know, nobody added explicit _potentially-throwing exception specifications_ (`noexcept(false)`) to ITK, so far.

**Comment by kaspermarstal** [comment]
Shall we just stick to ITK style? Or do it the proper way? What do you think?

**Comment by N-Dekker** [comment]
@kaspermarstal 
> Shall we just stick to ITK style? Or do it the proper way? What do you think?

I think: just merge! 

While it seems more proper to me to use `noexcept(false)`, It isn't common practice to do so.

**Comment by mstaring** [comment]
please go ahead and merge then

**Pull request merged**
