### PR TITLE
Reformat source code, using ITK clang-format file

### PR DESCRIPTION
**Pull request by N-Dekker**

### CODE REVIEW

**Review by dzenanz — COMMENTED** [review]
You might also want to apply this to *.in files (maybe manually see which ones are templates for C++ code, which ones for other things like CMake).

**Comment by N-Dekker** [comment]
> extra spaties?

@mstaring Thanks for having a check, Marius. I think the spaces that break `#include` into `#  include` are intended, as well in ITK, for example:

https://github.com/InsightSoftwareConsortium/ITK/blob/v5.1.1/Modules/Core/Common/include/itkAtanRegularizedHeavisideStepFunction.h#L87

**Comment by N-Dekker** [comment]
> You might also want to apply this to *.in files

@dzenanz Thanks for your suggestion. Many elastix *.in files do not have C++ code, but the following do:  

 - https://github.com/SuperElastix/elastix/blob/5.0.1/Common/OpenCL/ITKimprovements/itkOpenCLKernels.h.in
 - https://github.com/SuperElastix/elastix/blob/5.0.1/Components/Metrics/KNNGraphAlphaMutualInformation/KNN/ann_1.1/include/ANN/ANN.h.in
 - https://github.com/SuperElastix/elastix/blob/5.0.1/Core/elxVersionMacros.h.in
 - https://github.com/SuperElastix/elastix/blob/5.0.1/Core/Install/elxOpenCLSupportedImageTypes.h.in
 - https://github.com/SuperElastix/elastix/blob/5.0.1/Core/Install/elxSupportedImageTypes.h.in

However, it appears that clang-format breaks the CMake configure_file `@VAR@` variables. Did you also encounter that problem? For now I prefer to skip these files, but maybe they can be clang-formatted later.

**Comment by dzenanz** [comment]
Perhaps clang-format them once, then manually fix the @ breakages? That way the .in files will have the approximately correct style.

**Comment by mstaring** [comment]
approved

**Comment by N-Dekker** [comment]
> Perhaps clang-format them once, then manually fix the @ breakages?

@dzenanz Thanks for the suggestion but for the sake of time, I would like to just merge this PR now. However, I don't mind having another look at those in files later. I noticed the ITK *.in files also seem to be skipped by clang-format, for example: https://github.com/InsightSoftwareConsortium/ITK/blob/v5.1.1/CMake/itkImageIOFactoryRegisterManager.h.in#L22 should have the `{` at the next line.

**Comment by dzenanz** [comment]
Go ahead and merge. Later, having a pass at ITK's .in files would also be appreciated 😄

**Comment by mstaring** [comment]
could we use wildcards so that only .in files in certain directories get processed? or only in some directories they get excluded?

**Comment by N-Dekker** [comment]
> could we use wildcards so that only .in files in certain directories get processed?

@mstaring  The five C++ *.in files that were not included yet are all "*.h.in" files:
- Common/OpenCL/ITKimprovements/itkOpenCLKernels.h.in
- Components/Metrics/KNNGraphAlphaMutualInformation/KNN/ann_1.1/include/ANN/ANN.h.in
- Core/elxVersionMacros.h.in
- Core/Install/elxOpenCLSupportedImageTypes.h.in
- Core/Install/elxSupportedImageTypes.h.in

 For batch processing, it should be possible to only process "*.h.in" files. (Once we have figured out how to stop clang-format from messing up the `@VAR@` variables.)

However, I don't know yet how to tell the editor/IDE and the commit hook (to be added) that it should do so.

**Pull request merged**
