### PR TITLE
COMP: Add support for find_package(Elastix)

### PR DESCRIPTION
**Pull request by kaspermarstal**
This PR improves support for using Elastix in other projects. Elastix can now be imported via find_package(Elastix) and subsequent call to ELASTIX_USE_FILE. Targets are properly exported to an ElastixTargets.cmake file. The changes has been tested with SimpleElastix, which now correctly exports transitive dependencies from elastix.

### CODE REVIEW

**Comment by mstaring** [comment]
let's discuss during sprint

**Comment by mstaring** [comment]
Please check if the old functionality still works in SuperElastix with this change, for backwards compatibility. If that works, go ahead and merge this PR :-)

**Comment by kaspermarstal** [comment]
TODO: The elastix build is cached on AppVeyor and not build.

**Comment by kaspermarstal** [comment]
@fedorov It looks like `%ELASTIX_BUILD_DIR%` is now cached together with ITK and not therefore not build (https://ci.appveyor.com/project/kaspermarstal/elastix/build/1.0.32/job/1ktg9jmqc0u2r9bg). Do you know why? I am puzzled by this

**Comment by fedorov** [comment]
@kaspermarstal sorry I didn't follow up, very busy time here... Did you figure it out?

**Comment by kaspermarstal** [comment]
Yes, I think so, clearing caches seem to have worked and only ITK is cached now. Don't know why elastix was suddenly being cached as well. Anyway, thanks for reaching out.

**Comment by kaspermarstal** [comment]
@fedorov it sees the problem persists: https://ci.appveyor.com/project/kaspermarstal/elastix/build/job/75naeqe2djkst157. Manually cleared the caches prior to this build.

**Pull request merged**
