### PR TITLE
COMP: Use ITK 5.1.0 strongly typed enums in elxTransformBase

### PR DESCRIPTION
**Pull request by thewtex**
To address:

In file included from _deps/elastix_fetch-src/Core/ComponentBaseClasses/elxTransformBase.h:384:0,
                 from _deps/elastix_fetch-src/Core/Kernel/elxElastixTemplate.h:39,
                 from _deps/elastix_fetch-src/Core/Install/elxIncludes.h:39,
                 from _deps/elastix_fetch-src/Components/FixedImagePyramids/FixedRecursivePyramid/elxFixedRecursivePyramid.h:21,
                 from _deps/elastix_fetch-src/Components/FixedImagePyramids/FixedRecursivePyramid/elxFixedRecursivePyramid.cxx:19:
_deps/elastix_fetch-src/Core/ComponentBaseClasses/elxTransformBase.hxx: In member function ‘void itk::PixelTypeChangeCommand<T>::Execute(itk::Object*, const itk::EventObject&)’:
_deps/elastix_fetch-src/Core/ComponentBaseClasses/elxTransformBase.hxx:75:55: error: ‘VECTOR’ is not a member of ‘itk::ImageIOBase’
     castcaller->GetModifiableImageIO()->SetPixelType( ImageIOBase::VECTOR );
                                                       ^
_deps/elastix_fetch-src/Core/ComponentBaseClasses/elxTransformBase.hxx: In member function ‘void itk::PixelTypeChangeCommand<T>::Execute(const itk::Object*, const itk::EventObject&)’:
_deps/elastix_fetch-src/Core/ComponentBaseClasses/elxTransformBase.hxx:83:55: error: ‘VECTOR’ is not a member of ‘itk::ImageIOBase’
     castcaller->GetModifiableImageIO()->SetPixelType( ImageIOBase::VECTOR );

### CODE REVIEW

**Comment by N-Dekker** [comment]
@thewtex Did you build ITK with `ITK_LEGACY_REMOVE` ON or OFF? For the time being, I think it should be OFF for ITK 5.1, in order to preserve ITK 5.0.1 compatibility for elastix. Right?

**Comment by thewtex** [comment]
@N-Dekker ok, this could wait until elastix requires ITK 5.1.0. 

>  Did you build ITK with ITK_LEGACY_REMOVE ON or OFF? 

Yes, this is for the ITKElastix remote module / Python package, which requires the lastest and greatest ITK :-).

**Comment by N-Dekker** [comment]
> Yes, this is for the ITKElastix remote module / Python package, which requires the lastest and greatest ITK :-).

@thewtex Thanks for explaining, Matt. Unfortunately we do not have enough resources for elastix to actively support two different versions of ITK. As I just discussed with Marius @mstaring and Stefan @stefanklein However, once ITK 5.1 (final) is officially released, we intend to quickly upgrade the develop branch of elastix from ITK 5.0.1 to ITK 5.1.

Can you please give us an estimation of when ITK 5.1 is officially released?

**Comment by thewtex** [comment]
@N-Dekker makes sense.

The Git tag for ITK `v5.1.0` is out. I anticipate the final release announcement sometime in the next week.

**Comment by N-Dekker** [comment]
@thewtex Could you possibly still amend your commit (and force-push) just to adjust the following line of code in Testing/CI/Azure/ci.yml to the latest ITK version tag?

    ITKv5_VERSION: v5.0.1

https://github.com/SuperElastix/elastix/blob/56c2ebec4d99e15e76d1b1179e8ff156f669bf09/Testing/CI/Azure/ci.yml#L2 

It would be great to see your pull request going from red to green  😃

**Comment by thewtex** [comment]
@N-Dekker yes, done :-) :green_heart:

**Comment by N-Dekker** [comment]
Thanks for adjusting the ITK tag to v5.1.0 in the Elastix yml file, Matt! Unfortunately it appears that there are still some more compilation errors left now, at the Azure CI, including:

>   itkAdvancedBSplineDeformableTransformTest.cxx
d:\a\1\s\common\transforms\itkAdvancedBSplineDeformableTransformBase.h(78): error C2039: 'TransformCategoryType': is not a member of 'itk::AdvancedTransform<TScalarType,3,3>' [D:\a\1\Elastix-build\Testing\itkAdvancedBSplineDeformableTransformTest.vcxproj]

  ...

> d:\a\1\s\common\transforms\itkAdvancedBSplineDeformableTransformBase.h(270): error C2555: 'itk::AdvancedBSplineDeformableTransformBase<TScalarType,3>::GetTransformCategory': overriding virtual function return type differs and is not covariant from 'itk::Transform<TScalarType,3,3>::GetTransformCategory' [D:\a\1\Elastix-build\Testing\itkBSplineJacobianGradientPerformanceTest.vcxproj]

**Comment by thewtex** [comment]
@N-Dekker do you possibly have time to follow-up on this?

**Comment by N-Dekker** [comment]
@thewtex I think I finally have some time today! Unfortunately your PR still fails on the CI. I'll have a look.

**Comment by thewtex** [comment]
@N-Dekker awesome, thanks!

> error C2039: 'TransformCategoryType'

This is now `itk::TransformBaseTemplateEnums::TransformCategory`

https://github.com/InsightSoftwareConsortium/ITK/blob/8edb8659da2c21fd9dc4c6b2037f7311943a7b04/Modules/Core/Transform/include/itkTransformBase.h#L39-L54

**Comment by N-Dekker** [comment]
@thewtex Sorry for letting you wait, I'm just back from vacation (heatwave)! Thank you very much for moving the commit from PR #247 to this one, PR #245. Are these two commits together sufficient for you to build elastix + ITK 5.1 + ITK_LEGACY_REMOVE? I just tried your PR branch (elxTransformBase-strongly-typed-enum), and I still get many compilation errors, like:

> elxAdaptiveStochasticGradientDescent.cxx
> [elastix-source]\Common\Transforms\itkAdvancedBSplineDeformableTransformBase.h(78,32): error C2039: 'TransformCategoryType': is not a member of 'itk::AdvancedTransform<double,2,2>'

**Comment by N-Dekker** [comment]
@thewtex I guess we see many more legacy-remove errors on the CI than the ones you already fixed, because the CI includes Elastix CMake options `-DBUILD_TESTING=ON -DUSE_ALL_COMPONENTS=ON`

**Comment by N-Dekker** [comment]
FYI, I just did a `rebase develop` to get this PR back in sync with our develop branch. My intention is to do another `rebase develop` once pull request #269 is merged successfully.

**Comment by N-Dekker** [comment]
@thewtex Hi Matt, I just combined your two commits and mine into a single commit, that I would like to merge to the develop branch. Can you please check if it's still OK to you? I would like to merge tomorrow morning 😃

**Comment by N-Dekker** [comment]
Thank you very much for your contribution @thewtex I'll merge now, I hope it will allow you to get ITKElastix back in sync with SuperElastix/elastix 😃

**Pull request merged**
